import { AchievementRecord } from '../../types';

export const SEED_ACHIEVEMENTS: AchievementRecord[] = [
  {
    id: 'ach-first-challenge',
    code: 'FIRST_CHALLENGE',
    name: 'First Challenge',
    nameFr: 'Premier Défi',
    description: 'Complete your first cognitive challenge on BrainForge.',
    descriptionFr: 'Complétez votre premier défi cérébral sur BrainForge.',
    icon: 'Sparkles',
    category: 'general',
    requirementType: 'first_challenge',
    requirementValue: 1,
    xpBonus: 25,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ach-first-daily',
    code: 'FIRST_DAILY',
    name: 'Daily Initiate',
    nameFr: 'Initié Quotidien',
    description: 'Complete your very first Daily Challenge.',
    descriptionFr: 'Complétez votre tout premier Défi Quotidien.',
    icon: 'Calendar',
    category: 'general',
    requirementType: 'first_daily',
    requirementValue: 1,
    xpBonus: 50,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ach-streak-3',
    code: 'STREAK_3',
    name: '3-Day Streak',
    nameFr: 'Série de 3 Jours',
    description: 'Maintain a consecutive daily streak for 3 days.',
    descriptionFr: 'Maintenez une série quotidienne de 3 jours consécutifs.',
    icon: 'Flame',
    category: 'streak',
    requirementType: 'streak',
    requirementValue: 3,
    xpBonus: 50,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ach-streak-7',
    code: 'STREAK_7',
    name: '7-Day Streak',
    nameFr: 'Série de 7 Jours',
    description: 'Maintain a consecutive daily streak for a full week (7 days).',
    descriptionFr: 'Maintenez une série quotidienne pendant une semaine entière (7 jours).',
    icon: 'Flame',
    category: 'streak',
    requirementType: 'streak',
    requirementValue: 7,
    xpBonus: 100,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ach-streak-14',
    code: 'STREAK_14',
    name: '14-Day Streak',
    nameFr: 'Série de 14 Jours',
    description: 'Dedicate 14 consecutive days to cognitive challenges.',
    descriptionFr: 'Consacrez 14 jours consécutifs à vos défis cognitifs.',
    icon: 'Flame',
    category: 'streak',
    requirementType: 'streak',
    requirementValue: 14,
    xpBonus: 150,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ach-streak-30',
    code: 'STREAK_30',
    name: 'Monthly Master',
    nameFr: 'Maître du Mois',
    description: 'Achieve an unbroken 30-day streak of daily practice.',
    descriptionFr: 'Atteignez une série ininterrompue de 30 jours de pratique quotidienne.',
    icon: 'Crown',
    category: 'streak',
    requirementType: 'streak',
    requirementValue: 30,
    xpBonus: 300,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ach-level-5',
    code: 'LEVEL_5',
    name: 'Level 5 Achieved',
    nameFr: 'Niveau 5 Atteint',
    description: 'Reach Level 5 by accumulating XP across challenges.',
    descriptionFr: 'Atteignez le Niveau 5 en accumulant de l’XP à travers vos défis.',
    icon: 'Award',
    category: 'level',
    requirementType: 'level',
    requirementValue: 5,
    xpBonus: 100,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ach-quiz-master',
    code: 'QUIZ_MASTER',
    name: 'Quiz Master',
    nameFr: 'Maître du Quiz',
    description: 'Score 100% on any Quiz challenge.',
    descriptionFr: 'Obtenez 100% de bonnes réponses sur une épreuve de Quiz.',
    icon: 'CheckCircle2',
    category: 'performance',
    requirementType: 'quiz_score',
    requirementValue: 100,
    xpBonus: 50,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ach-memory-master',
    code: 'MEMORY_MASTER',
    name: 'Memory Prodigy',
    nameFr: 'Prodige de la Mémoire',
    description: 'Score 90% or higher on a Memory challenge.',
    descriptionFr: 'Obtenez 90% ou plus sur un défi de mémorisation séquentielle.',
    icon: 'Brain',
    category: 'performance',
    requirementType: 'memory_score',
    requirementValue: 90,
    xpBonus: 50,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ach-reaction-master',
    code: 'REACTION_MASTER',
    name: 'Lightning Reflex',
    nameFr: 'Réflexe Éclair',
    description: 'Score 100% on a Reaction challenge without false start.',
    descriptionFr: 'Obtenez 100% sur une épreuve de réaction sans faux départ.',
    icon: 'Zap',
    category: 'performance',
    requirementType: 'reaction_score',
    requirementValue: 100,
    xpBonus: 50,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ach-speed-master',
    code: 'SPEED_MASTER',
    name: 'Speed Master',
    nameFr: 'Maître de la Vitesse',
    description: 'Achieve at least 90% accuracy in speed challenges.',
    descriptionFr: 'Atteignez au moins 90% de précision sur les épreuves de vitesse.',
    icon: 'Target',
    category: 'performance',
    requirementType: 'speed_score',
    requirementValue: 90,
    xpBonus: 50,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'ach-challenge-10',
    code: 'CHALLENGE_10',
    name: 'Dedicated Challenger',
    nameFr: 'Challenger Assidu',
    description: 'Complete 10 total challenges on BrainForge.',
    descriptionFr: 'Complétez 10 défis au total sur BrainForge.',
    icon: 'Medal',
    category: 'general',
    requirementType: 'total_challenges',
    requirementValue: 10,
    xpBonus: 75,
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];
