import { RawChallengeRecord } from '../engine/ChallengeEngine';

export const SEED_CHALLENGES: RawChallengeRecord[] = [
  // ===================== QUIZ (10 challenges) =====================
  {
    id: 'quiz-001',
    type: 'quiz',
    skill: 'knowledge',
    difficulty: 1,
    status: 'published',
    titleFr: 'Capitale du Canada',
    titleEn: 'Capital of Canada',
    descriptionFr: 'Identifiez la capitale fédérale du Canada.',
    descriptionEn: 'Identify the federal capital of Canada.',
    version: 1,
    contentFr: {
      question: 'Quelle est la capitale fédérale du Canada ?',
      options: [
        { id: 'a', label: 'Toronto' },
        { id: 'b', label: 'Montréal' },
        { id: 'c', label: 'Ottawa' },
        { id: 'd', label: 'Vancouver' },
      ],
    },
    contentEn: {
      question: 'What is the capital of Canada?',
      options: [
        { id: 'a', label: 'Toronto' },
        { id: 'b', label: 'Montreal' },
        { id: 'c', label: 'Ottawa' },
        { id: 'd', label: 'Vancouver' },
      ],
    },
    answerKey: { correctOptionId: 'c' },
  },
  {
    id: 'quiz-002',
    type: 'quiz',
    skill: 'knowledge',
    difficulty: 1,
    status: 'published',
    titleFr: 'Couleurs Primaires',
    titleEn: 'Primary Colors',
    descriptionFr: 'Théorie fondamentale de la couleur additive.',
    descriptionEn: 'Fundamental color theory.',
    version: 1,
    contentFr: {
      question: 'Laquelle de ces couleurs n’est PAS une couleur primaire en peinture traditionnelle ?',
      options: [
        { id: 'a', label: 'Rouge' },
        { id: 'b', label: 'Bleu' },
        { id: 'c', label: 'Vert' },
        { id: 'd', label: 'Jaune' },
      ],
    },
    contentEn: {
      question: 'Which of the following is NOT a traditional painter primary color?',
      options: [
        { id: 'a', label: 'Red' },
        { id: 'b', label: 'Blue' },
        { id: 'c', label: 'Green' },
        { id: 'd', label: 'Yellow' },
      ],
    },
    answerKey: { correctOptionId: 'c' },
  },
  {
    id: 'quiz-003',
    type: 'quiz',
    skill: 'logic',
    difficulty: 2,
    status: 'published',
    titleFr: 'Syllogisme Logique',
    titleEn: 'Logical Syllogism',
    descriptionFr: 'Déduction formelle rigoureuse.',
    descriptionEn: 'Formal logical deduction.',
    version: 1,
    contentFr: {
      question: 'Tous les félins sont des mammifères. Certains félins nagent. Que peut-on conclure avec certitude ?',
      options: [
        { id: 'a', label: 'Tous les mammifères nagent' },
        { id: 'b', label: 'Certains mammifères nagent' },
        { id: 'c', label: 'Aucun félin ne vole' },
        { id: 'd', label: 'Tous les félins aiment l’eau' },
      ],
    },
    contentEn: {
      question: 'All felines are mammals. Some felines swim. What conclusion is mathematically guaranteed?',
      options: [
        { id: 'a', label: 'All mammals swim' },
        { id: 'b', label: 'Some mammals swim' },
        { id: 'c', label: 'No felines fly' },
        { id: 'd', label: 'All felines like water' },
      ],
    },
    answerKey: { correctOptionId: 'b' },
  },
  {
    id: 'quiz-004',
    type: 'quiz',
    skill: 'knowledge',
    difficulty: 2,
    status: 'published',
    titleFr: 'Antonyme d’Éphémère',
    titleEn: 'Antonym of Ephemeral',
    descriptionFr: 'Précision lexicale et sémantique.',
    descriptionEn: 'Lexical and semantic precision.',
    version: 1,
    contentFr: {
      question: 'Quel est l’antonyme le plus exact de l’adjectif "éphémère" ?',
      options: [
        { id: 'a', label: 'Fugace' },
        { id: 'b', label: 'Pérenne' },
        { id: 'c', label: 'Illusoire' },
        { id: 'd', label: 'Instantané' },
      ],
    },
    contentEn: {
      question: 'What is the most precise antonym of "ephemeral"?',
      options: [
        { id: 'a', label: 'Fleeting' },
        { id: 'b', label: 'Perennial' },
        { id: 'c', label: 'Transient' },
        { id: 'd', label: 'Momentary' },
      ],
    },
    answerKey: { correctOptionId: 'b' },
  },
  {
    id: 'quiz-005',
    type: 'quiz',
    skill: 'knowledge',
    difficulty: 1,
    status: 'published',
    titleFr: 'Système Solaire',
    titleEn: 'Solar System',
    descriptionFr: 'Ordre orbital des planètes.',
    descriptionEn: 'Orbital order of planets.',
    version: 1,
    contentFr: {
      question: 'Quelle est la planète la plus proche du Soleil ?',
      options: [
        { id: 'a', label: 'Vénus' },
        { id: 'b', label: 'Mercure' },
        { id: 'c', label: 'Mars' },
        { id: 'd', label: 'Terre' },
      ],
    },
    contentEn: {
      question: 'Which planet is closest to the Sun?',
      options: [
        { id: 'a', label: 'Venus' },
        { id: 'b', label: 'Mercury' },
        { id: 'c', label: 'Mars' },
        { id: 'd', label: 'Earth' },
      ],
    },
    answerKey: { correctOptionId: 'b' },
  },
  {
    id: 'quiz-006',
    type: 'quiz',
    skill: 'logic',
    difficulty: 3,
    status: 'published',
    titleFr: 'Le Problème de la Balle',
    titleEn: 'Bat and Ball Problem',
    descriptionFr: 'Biais cognitif et calcul intuitif contre délibéré.',
    descriptionEn: 'Cognitive reflection test on dual-process thinking.',
    version: 1,
    contentFr: {
      question: 'Une raquette et une balle coûtent 1,10 € au total. La raquette coûte 1,00 € de plus que la balle. Combien coûte la balle ?',
      options: [
        { id: 'a', label: '0,10 €' },
        { id: 'b', label: '0,05 €' },
        { id: 'c', label: '0,01 €' },
        { id: 'd', label: '0,02 €' },
      ],
    },
    contentEn: {
      question: 'A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?',
      options: [
        { id: 'a', label: '$0.10' },
        { id: 'b', label: '$0.05' },
        { id: 'c', label: '$0.01' },
        { id: 'd', label: '$0.02' },
      ],
    },
    answerKey: { correctOptionId: 'b' },
  },
  {
    id: 'quiz-007',
    type: 'quiz',
    skill: 'knowledge',
    difficulty: 2,
    status: 'published',
    titleFr: 'Vitesse de la Lumière',
    titleEn: 'Speed of Light',
    descriptionFr: 'Constante universelle dans le vide.',
    descriptionEn: 'Universal physical constant in vacuum.',
    version: 1,
    contentFr: {
      question: 'À combien s’élève approximativement la vitesse de la lumière dans le vide ?',
      options: [
        { id: 'a', label: '30 000 km/s' },
        { id: 'b', label: '300 000 km/s' },
        { id: 'c', label: '3 000 000 km/s' },
        { id: 'd', label: '300 km/s' },
      ],
    },
    contentEn: {
      question: 'What is the approximate speed of light in vacuum?',
      options: [
        { id: 'a', label: '30,000 km/s' },
        { id: 'b', label: '300,000 km/s' },
        { id: 'c', label: '3,000,000 km/s' },
        { id: 'd', label: '300 km/s' },
      ],
    },
    answerKey: { correctOptionId: 'b' },
  },
  {
    id: 'quiz-008',
    type: 'quiz',
    skill: 'knowledge',
    difficulty: 3,
    status: 'published',
    titleFr: 'Vocabulaire Soutenu',
    titleEn: 'Advanced Vocabulary',
    descriptionFr: 'Sens précis du mot "Pléthore".',
    descriptionEn: 'Precise meaning of "Ubiquitous".',
    version: 1,
    contentFr: {
      question: 'Que signifie une "pléthore" de quelque chose ?',
      options: [
        { id: 'a', label: 'Une pénurie extrême' },
        { id: 'b', label: 'Une abondance excessive' },
        { id: 'c', label: 'Une variété équilibrée' },
        { id: 'd', label: 'Une disparition progressive' },
      ],
    },
    contentEn: {
      question: 'What does the word "ubiquitous" mean?',
      options: [
        { id: 'a', label: 'Extremely rare' },
        { id: 'b', label: 'Found everywhere' },
        { id: 'c', label: 'Highly ancient' },
        { id: 'd', label: 'Completely concealed' },
      ],
    },
    answerKey: { correctOptionId: 'b' },
  },
  {
    id: 'quiz-009',
    type: 'quiz',
    skill: 'knowledge',
    difficulty: 1,
    status: 'published',
    titleFr: 'Année Bissextile',
    titleEn: 'Leap Year',
    descriptionFr: 'Arithmétique calendaire.',
    descriptionEn: 'Calendar arithmetic.',
    version: 1,
    contentFr: {
      question: 'Combien de jours compte une année bissextile ?',
      options: [
        { id: 'a', label: '364' },
        { id: 'b', label: '365' },
        { id: 'c', label: '366' },
        { id: 'd', label: '367' },
      ],
    },
    contentEn: {
      question: 'How many days does a leap year contain?',
      options: [
        { id: 'a', label: '364' },
        { id: 'b', label: '365' },
        { id: 'c', label: '366' },
        { id: 'd', label: '367' },
      ],
    },
    answerKey: { correctOptionId: 'c' },
  },
  {
    id: 'quiz-010',
    type: 'quiz',
    skill: 'logic',
    difficulty: 3,
    status: 'published',
    titleFr: 'Course et Dépassement',
    titleEn: 'Race Placement Logic',
    descriptionFr: 'Raisonnement spatial dynamique.',
    descriptionEn: 'Dynamic spatial reasoning.',
    version: 1,
    contentFr: {
      question: 'Dans une course à pied, vous dépassez la personne en 2e position. À quelle place êtes-vous ?',
      options: [
        { id: 'a', label: '1ère place' },
        { id: 'b', label: '2e place' },
        { id: 'c', label: '3e place' },
        { id: 'd', label: 'Dernière place' },
      ],
    },
    contentEn: {
      question: 'In a marathon, you overtake the person in 2nd place. What position are you now in?',
      options: [
        { id: 'a', label: '1st place' },
        { id: 'b', label: '2nd place' },
        { id: 'c', label: '3rd place' },
        { id: 'd', label: 'Last place' },
      ],
    },
    answerKey: { correctOptionId: 'b' },
  },

  // ===================== PATTERN (10 challenges) =====================
  {
    id: 'pattern-001',
    type: 'pattern',
    skill: 'logic',
    difficulty: 1,
    status: 'published',
    titleFr: 'Suite Paire Simple',
    titleEn: 'Simple Even Progression',
    descriptionFr: 'Trouvez la prochaine valeur dans la suite.',
    descriptionEn: 'Find the next value in the progression.',
    version: 1,
    contentFr: {
      sequence: [2, 4, 6, 8],
      options: [9, 10, 11, 12],
      hint: '+2 à chaque étape',
    },
    contentEn: {
      sequence: [2, 4, 6, 8],
      options: [9, 10, 11, 12],
      hint: '+2 at each step',
    },
    answerKey: { correctOption: 10 },
  },
  {
    id: 'pattern-002',
    type: 'pattern',
    skill: 'logic',
    difficulty: 1,
    status: 'published',
    titleFr: 'Multiple de Cinq',
    titleEn: 'Multiples of Five',
    descriptionFr: 'Déterminez le terme suivant.',
    descriptionEn: 'Determine the following term.',
    version: 1,
    contentFr: {
      sequence: [5, 10, 15, 20],
      options: [22, 24, 25, 30],
    },
    contentEn: {
      sequence: [5, 10, 15, 20],
      options: [22, 24, 25, 30],
    },
    answerKey: { correctOption: 25 },
  },
  {
    id: 'pattern-003',
    type: 'pattern',
    skill: 'logic',
    difficulty: 1,
    status: 'published',
    titleFr: 'Puissances de Deux',
    titleEn: 'Powers of Two',
    descriptionFr: 'Doublement successif des termes.',
    descriptionEn: 'Successive doubling progression.',
    version: 1,
    contentFr: {
      sequence: [1, 2, 4, 8],
      options: [12, 14, 16, 18],
    },
    contentEn: {
      sequence: [1, 2, 4, 8],
      options: [12, 14, 16, 18],
    },
    answerKey: { correctOption: 16 },
  },
  {
    id: 'pattern-004',
    type: 'pattern',
    skill: 'logic',
    difficulty: 2,
    status: 'published',
    titleFr: 'Progression Géométrique ×3',
    titleEn: 'Geometric Progression ×3',
    descriptionFr: 'Multiplication par trois à chaque pas.',
    descriptionEn: 'Multiplication by three at each iteration.',
    version: 1,
    contentFr: {
      sequence: [3, 9, 27, 81],
      options: [162, 243, 324, 405],
    },
    contentEn: {
      sequence: [3, 9, 27, 81],
      options: [162, 243, 324, 405],
    },
    answerKey: { correctOption: 243 },
  },
  {
    id: 'pattern-005',
    type: 'pattern',
    skill: 'logic',
    difficulty: 2,
    status: 'published',
    titleFr: 'Suite de Fibonacci',
    titleEn: 'Fibonacci Sequence',
    descriptionFr: 'Somme des deux termes précédents.',
    descriptionEn: 'Sum of the previous two terms.',
    version: 1,
    contentFr: {
      sequence: [1, 1, 2, 3, 5, 8],
      options: [11, 12, 13, 15],
    },
    contentEn: {
      sequence: [1, 1, 2, 3, 5, 8],
      options: [11, 12, 13, 15],
    },
    answerKey: { correctOption: 13 },
  },
  {
    id: 'pattern-006',
    type: 'pattern',
    skill: 'logic',
    difficulty: 2,
    status: 'published',
    titleFr: 'Régression Arithmétique (-7)',
    titleEn: 'Arithmetic Regression (-7)',
    descriptionFr: 'Soustraction constante.',
    descriptionEn: 'Constant subtraction step.',
    version: 1,
    contentFr: {
      sequence: [100, 93, 86, 79],
      options: [70, 71, 72, 74],
    },
    contentEn: {
      sequence: [100, 93, 86, 79],
      options: [70, 71, 72, 74],
    },
    answerKey: { correctOption: 72 },
  },
  {
    id: 'pattern-007',
    type: 'pattern',
    skill: 'logic',
    difficulty: 3,
    status: 'published',
    titleFr: 'Nombres Premiers Consécutifs',
    titleEn: 'Consecutive Prime Numbers',
    descriptionFr: 'Reconnaissance de la série des nombres premiers.',
    descriptionEn: 'Identify the next prime integer.',
    version: 1,
    contentFr: {
      sequence: [2, 3, 5, 7, 11],
      options: [12, 13, 14, 15],
    },
    contentEn: {
      sequence: [2, 3, 5, 7, 11],
      options: [12, 13, 14, 15],
    },
    answerKey: { correctOption: 13 },
  },
  {
    id: 'pattern-008',
    type: 'pattern',
    skill: 'logic',
    difficulty: 3,
    status: 'published',
    titleFr: 'Carrés Parfaits',
    titleEn: 'Perfect Squares',
    descriptionFr: 'Série quadratique n².',
    descriptionEn: 'Quadratic series n².',
    version: 1,
    contentFr: {
      sequence: [1, 4, 9, 16, 25],
      options: [30, 34, 36, 49],
    },
    contentEn: {
      sequence: [1, 4, 9, 16, 25],
      options: [30, 34, 36, 49],
    },
    answerKey: { correctOption: 36 },
  },
  {
    id: 'pattern-009',
    type: 'pattern',
    skill: 'logic',
    difficulty: 2,
    status: 'published',
    titleFr: 'Suite Alphabétique Sautée',
    titleEn: 'Alternating Alphabet',
    descriptionFr: 'Saut d’une lettre dans l’alphabet.',
    descriptionEn: 'Skip one letter in alphabetical sequence.',
    version: 1,
    contentFr: {
      sequence: ['A', 'C', 'E', 'G'],
      options: ['H', 'I', 'J', 'K'],
    },
    contentEn: {
      sequence: ['A', 'C', 'E', 'G'],
      options: ['H', 'I', 'J', 'K'],
    },
    answerKey: { correctOption: 'I' },
  },
  {
    id: 'pattern-010',
    type: 'pattern',
    skill: 'logic',
    difficulty: 3,
    status: 'published',
    titleFr: 'Cubes Parfaits n³',
    titleEn: 'Cubic Numbers n³',
    descriptionFr: 'Progression cubique.',
    descriptionEn: 'Cubic sequence progression.',
    version: 1,
    contentFr: {
      sequence: [1, 8, 27, 64],
      options: [100, 125, 128, 216],
    },
    contentEn: {
      sequence: [1, 8, 27, 64],
      options: [100, 125, 128, 216],
    },
    answerKey: { correctOption: 125 },
  },

  // ===================== MEMORY (5 challenges) =====================
  {
    id: 'memory-001',
    type: 'memory',
    skill: 'memory',
    difficulty: 1,
    status: 'published',
    titleFr: 'Rappel Alphanumérique Court',
    titleEn: 'Short Alphanumeric Recall',
    descriptionFr: 'Mémorisez 4 symboles pendant 3 secondes.',
    descriptionEn: 'Memorize 4 symbols for 3 seconds.',
    version: 1,
    contentFr: {
      items: ['7', 'B', '3', 'F'],
      displayDurationMs: 3000,
      recallMode: 'sequence',
    },
    contentEn: {
      items: ['7', 'B', '3', 'F'],
      displayDurationMs: 3000,
      recallMode: 'sequence',
    },
    answerKey: { items: ['7', 'B', '3', 'F'] },
  },
  {
    id: 'memory-002',
    type: 'memory',
    skill: 'memory',
    difficulty: 1,
    status: 'published',
    titleFr: 'Séquence des 5 Éléments',
    titleEn: 'Five-Element Sequence',
    descriptionFr: 'Mémorisez la séquence exacte de 5 caractères.',
    descriptionEn: 'Memorize the exact 5-character sequence.',
    version: 1,
    contentFr: {
      items: ['A', '7', 'K', '3', 'P'],
      displayDurationMs: 3000,
      recallMode: 'sequence',
    },
    contentEn: {
      items: ['A', '7', 'K', '3', 'P'],
      displayDurationMs: 3000,
      recallMode: 'sequence',
    },
    answerKey: { items: ['A', '7', 'K', '3', 'P'] },
  },
  {
    id: 'memory-003',
    type: 'memory',
    skill: 'memory',
    difficulty: 2,
    status: 'published',
    titleFr: 'Capacité de Travail (6 items)',
    titleEn: 'Working Memory (6 items)',
    descriptionFr: 'Mémorisez une série de 6 caractères mixtes.',
    descriptionEn: 'Memorize a sequence of 6 mixed characters.',
    version: 1,
    contentFr: {
      items: ['9', 'X', '4', 'M', '2', 'L'],
      displayDurationMs: 3500,
      recallMode: 'sequence',
    },
    contentEn: {
      items: ['9', 'X', '4', 'M', '2', 'L'],
      displayDurationMs: 3500,
      recallMode: 'sequence',
    },
    answerKey: { items: ['9', 'X', '4', 'M', '2', 'L'] },
  },
  {
    id: 'memory-004',
    type: 'memory',
    skill: 'memory',
    difficulty: 2,
    status: 'published',
    titleFr: 'Symboles Helléniques',
    titleEn: 'Hellenic Symbols',
    descriptionFr: 'Mémorisez l’ordre de 6 lettres grecques.',
    descriptionEn: 'Memorize the order of 6 Greek glyphs.',
    version: 1,
    contentFr: {
      items: ['Δ', 'Ω', 'Σ', 'Ψ', 'Φ', 'λ'],
      displayDurationMs: 3800,
      recallMode: 'sequence',
    },
    contentEn: {
      items: ['Δ', 'Ω', 'Σ', 'Ψ', 'Φ', 'λ'],
      displayDurationMs: 3800,
      recallMode: 'sequence',
    },
    answerKey: { items: ['Δ', 'Ω', 'Σ', 'Ψ', 'Φ', 'λ'] },
  },
  {
    id: 'memory-005',
    type: 'memory',
    skill: 'memory',
    difficulty: 3,
    status: 'published',
    titleFr: 'Empan Visuo-Spatial (7 items)',
    titleEn: 'Visuo-Spatial Span (7 items)',
    descriptionFr: 'Test d’empan mémoriel supérieur (Miller 7±2).',
    descriptionEn: 'High memory span trial (Miller 7±2).',
    version: 1,
    contentFr: {
      items: ['8', 'R', '5', 'T', '9', 'W', '1'],
      displayDurationMs: 4000,
      recallMode: 'sequence',
    },
    contentEn: {
      items: ['8', 'R', '5', 'T', '9', 'W', '1'],
      displayDurationMs: 4000,
      recallMode: 'sequence',
    },
    answerKey: { items: ['8', 'R', '5', 'T', '9', 'W', '1'] },
  },

  // ===================== REACTION (5 challenges) =====================
  {
    id: 'reaction-001',
    type: 'reaction',
    skill: 'speed',
    difficulty: 1,
    status: 'published',
    titleFr: 'Réflexe Visuel Standard',
    titleEn: 'Standard Visual Reflex',
    descriptionFr: 'Attendez le signal visuel et cliquez dès son apparition.',
    descriptionEn: 'Wait for the visual signal and click immediately.',
    version: 1,
    contentFr: {
      prompt: 'Cliquez dès que le cercle vert apparaît. Attention aux faux départs !',
      minDelayMs: 1200,
      maxDelayMs: 2800,
      targetAction: 'click',
    },
    contentEn: {
      prompt: 'Click as soon as the green stimulus appears. Avoid false starts!',
      minDelayMs: 1200,
      maxDelayMs: 2800,
      targetAction: 'click',
    },
    answerKey: { minValidReactionMs: 100 },
  },
  {
    id: 'reaction-002',
    type: 'reaction',
    skill: 'speed',
    difficulty: 1,
    status: 'published',
    titleFr: 'Déclencheur Rapide',
    titleEn: 'Rapid Trigger',
    descriptionFr: 'Intervalle d’attente court et concentré.',
    descriptionEn: 'Short and focused delay interval.',
    version: 1,
    contentFr: {
      prompt: 'Concentration maximale. Dès le flash lumineux, réagissez instantanément.',
      minDelayMs: 1000,
      maxDelayMs: 2200,
      targetAction: 'click',
    },
    contentEn: {
      prompt: 'Peak concentration. React instantly as soon as the flash triggers.',
      minDelayMs: 1000,
      maxDelayMs: 2200,
      targetAction: 'click',
    },
    answerKey: { minValidReactionMs: 100 },
  },
  {
    id: 'reaction-003',
    type: 'reaction',
    skill: 'speed',
    difficulty: 2,
    status: 'published',
    titleFr: 'Attente Prolongée',
    titleEn: 'Sustained Vigilance',
    descriptionFr: 'Maintien de la vigilance sur un intervalle imprévisible.',
    descriptionEn: 'Maintain vigilance over an unpredictable interval.',
    version: 1,
    contentFr: {
      prompt: 'Le signal peut tarder. Maintenez votre attention sans anticiper.',
      minDelayMs: 1800,
      maxDelayMs: 3400,
      targetAction: 'click',
    },
    contentEn: {
      prompt: 'Signal may be delayed. Maintain focus without jumping the gun.',
      minDelayMs: 1800,
      maxDelayMs: 3400,
      targetAction: 'click',
    },
    answerKey: { minValidReactionMs: 100 },
  },
  {
    id: 'reaction-004',
    type: 'reaction',
    skill: 'speed',
    difficulty: 2,
    status: 'published',
    titleFr: 'Rythme Variable',
    titleEn: 'Variable Rhythm',
    descriptionFr: 'Délai stochastique modéré.',
    descriptionEn: 'Moderate stochastic delay.',
    version: 1,
    contentFr: {
      prompt: 'Synchronisez votre œil et votre index. Réaction pure.',
      minDelayMs: 1500,
      maxDelayMs: 3000,
      targetAction: 'click',
    },
    contentEn: {
      prompt: 'Synchronize visual focus and motor response. Pure reaction.',
      minDelayMs: 1500,
      maxDelayMs: 3000,
      targetAction: 'click',
    },
    answerKey: { minValidReactionMs: 100 },
  },
  {
    id: 'reaction-005',
    type: 'reaction',
    skill: 'speed',
    difficulty: 3,
    status: 'published',
    titleFr: 'Flash Haute Précision',
    titleEn: 'Precision Burst',
    descriptionFr: 'Intervalle étendu exigeant une inhibition motrice parfaite.',
    descriptionEn: 'Extended interval requiring strict motor inhibition.',
    version: 1,
    contentFr: {
      prompt: 'Inhibition motrice stricte. Tout clic anticipé invalidera l’essai.',
      minDelayMs: 2000,
      maxDelayMs: 4000,
      targetAction: 'click',
    },
    contentEn: {
      prompt: 'Strict motor inhibition. Any early click will invalidate the trial.',
      minDelayMs: 2000,
      maxDelayMs: 4000,
      targetAction: 'click',
    },
    answerKey: { minValidReactionMs: 100 },
  },
];
